# Generated by Django 5.1.4 on 2024-12-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_registrationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='code',
            field=models.CharField(default='3JGVPP', max_length=6, unique=True),
        ),
    ]
